# Generated by Django 3.1.7 on 2021-05-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='role',
            field=models.CharField(choices=[('H', 'HR'), ('C', 'CEO'), ('M', 'MANAGER'), ('S', 'SE'), ('J', 'JE'), ('E', 'EMP')], default=None, max_length=5),
        ),
    ]
