# Generated by Django 3.1.7 on 2021-05-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20210529_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdetails',
            name='employeeid',
        ),
    ]
