# Generated by Django 3.1.7 on 2021-05-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_remove_empdetails_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdetails',
            name='designation',
        ),
    ]
