# Generated by Django 3.1.7 on 2021-05-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_remove_empdetails_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='teamname',
            new_name='team_name',
        ),
    ]
